name: Deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fmt-lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Check
        run: deno check mod.ts
